import { useMemo, useState, type FormEvent } from 'react'
import { formatMoney } from '../data/chicken'
import type { GroceryProduct } from '../data/grocery'
import { getStockStatus, inventoryStore, isLowStock, isOutOfStock, stockValue, type AdjustmentReason, type InventoryMovementType } from '../data/inventory'
import { storageAdapter } from '../services/storageAdapter'
import { adjustStock } from '../services/supabase/inventoryService'

type InventoryProps = { items: GroceryProduct[]; onChange: (items: GroceryProduct[]) => void; userName: string }
const statusClass = (status: string) => status.toLowerCase().replaceAll(' ', '-')
const reasons: AdjustmentReason[] = ['Stock Count Correction', 'Damaged', 'Expired', 'Lost', 'Found', 'Other']

export function Inventory({ items, onChange, userName }: InventoryProps) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [filter, setFilter] = useState('All'); const [sort, setSort] = useState('name'); const [selected, setSelected] = useState<GroceryProduct | null>(null); const [operation, setOperation] = useState<'adjust' | 'return' | 'count' | null>(null); const categories = ['All', ...Array.from(new Set(items.map(item => item.category))).sort()]
  const filtered = useMemo(() => items.filter(item => { const status = getStockStatus(item); const matchesQuery = item.name.toLowerCase().includes(query.toLowerCase()) || item.barcode.includes(query); const matchesCategory = category === 'All' || item.category === category; const matchesFilter = filter === 'All' || (filter === 'Active' && item.active) || (filter === 'Inactive' && !item.active) || (filter === 'Low Stock' && isLowStock(item)) || (filter === 'Out of Stock' && isOutOfStock(item)); return matchesQuery && matchesCategory && matchesFilter && status }).sort((a, b) => sort === 'stock' ? a.stockQuantity - b.stockQuantity : sort === 'selling' ? a.sellingPrice - b.sellingPrice : sort === 'cost' ? a.costPrice - b.costPrice : sort === 'updated' ? b.updatedAt.localeCompare(a.updatedAt) : a.name.localeCompare(b.name)), [items, query, category, filter, sort])
  const activeItems = items.filter(item => item.active); const lowStock = activeItems.filter(isLowStock); const outOfStock = activeItems.filter(isOutOfStock); const totalValue = activeItems.reduce((sum, item) => sum + stockValue(item), 0)
  const applyChange = async (productId: string, delta: number, type: InventoryMovementType, reason: string, notes: string) => { if (storageAdapter.isSupabase()) { const result = await adjustStock(productId, delta, type, reason, notes); const next = items.map(item => item.id === productId ? { ...item, stockQuantity: result.new_stock, updatedAt: new Date().toISOString() } : item); onChange(next); setSelected(next.find(item => item.id === productId) || null); setOperation(null); return } const next = inventoryStore.applyLocalChange(items, productId, delta, type, reason, notes, userName); onChange(next); setSelected(next.find(item => item.id === productId) || null); setOperation(null) }
  return <section className="prices-page inventory-page"><header className="page-header"><div><small>INVENTORY CONTROL</small><h1>Inventory</h1><p>Track grocery stock, valuation and movement history.</p></div></header><div className="inventory-summary"><div><small>ACTIVE PRODUCTS</small><b>{activeItems.length}</b></div><div><small>STOCK VALUE</small><b>{formatMoney(totalValue)}</b></div><button onClick={() => setFilter('Low Stock')}><small>LOW STOCK</small><b>{lowStock.length}</b></button><button onClick={() => setFilter('Out of Stock')}><small>OUT OF STOCK</small><b>{outOfStock.length}</b></button></div><div className="inventory-tools"><input className="product-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search product or barcode" /><select value={category} onChange={event => setCategory(event.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={filter} onChange={event => setFilter(event.target.value)}>{['All', 'Low Stock', 'Out of Stock', 'Active', 'Inactive'].map(item => <option key={item}>{item}</option>)}</select><select value={sort} onChange={event => setSort(event.target.value)}><option value="name">Name</option><option value="stock">Stock</option><option value="cost">Cost price</option><option value="selling">Selling price</option><option value="updated">Last updated</option></select></div><section className="price-table inventory-table"><div className="price-row table-head"><span>Product / Barcode</span><span>Stock / Unit</span><span>Cost / Selling</span><span>Stock Value</span><span>Status</span><span>Action</span></div>{filtered.map(item => { const status = getStockStatus(item); return <button className="price-row inventory-row" key={item.id} onClick={() => setSelected(item)}><span><b>{item.name}</b><small>{item.barcode || 'No barcode'} · {item.category}</small></span><span>{item.stockQuantity} {item.unit}<small>Minimum {item.lowStockLevel}</small></span><span>{formatMoney(item.costPrice)}<small>{formatMoney(item.sellingPrice)} sell</small></span><span>{formatMoney(stockValue(item))}</span><span><em className={`stock-status ${statusClass(status)}`}>{status}</em></span><span><b className="edit">Details</b></span></button> })}</section>{selected && <Details product={selected} userName={userName} close={() => { setSelected(null); setOperation(null) }} openOperation={setOperation} operation={operation} applyChange={applyChange} />}</section>
}

function Details({ product, userName, close, openOperation, operation, applyChange }: { product: GroceryProduct; userName: string; close: () => void; openOperation: (operation: 'adjust' | 'return' | 'count' | null) => void; operation: 'adjust' | 'return' | 'count' | null; applyChange: (productId: string, delta: number, type: InventoryMovementType, reason: string, notes: string) => Promise<void> }) {
  const movements = inventoryStore.getProductMovements(product.id)
  return <div className="shade"><section className="dialog inventory-dialog"><header><div><small>PRODUCT DETAILS</small><h2>{product.name}</h2></div><button onClick={close}>×</button></header><div className="inventory-detail-grid"><span>Barcode<strong>{product.barcode || 'None'}</strong></span><span>Current stock<strong>{product.stockQuantity} {product.unit}</strong></span><span>Cost price<strong>{formatMoney(product.costPrice)}</strong></span><span>Selling price<strong>{formatMoney(product.sellingPrice)}</strong></span><span>Stock value<strong>{formatMoney(stockValue(product))}</strong></span><span>Status<strong><em className={`stock-status ${statusClass(getStockStatus(product))}`}>{getStockStatus(product)}</em></strong></span></div><div className="inventory-actions"><button className="primary" onClick={() => openOperation('adjust')}>Adjust Stock</button><button className="edit" onClick={() => openOperation('return')}>Process Return</button><button className="edit" onClick={() => openOperation('count')}>Stock Count</button></div><h3>Movement History</h3><div className="movement-list">{movements.length ? movements.map(item => <div className="movement-row" key={item.id}><span>{item.date}<small>{item.time}</small></span><span><b>{item.type}</b><small>{item.reason || 'No reason'}</small></span><span className={item.quantity < 0 ? 'movement-negative' : 'movement-positive'}>{item.quantity > 0 ? '+' : ''}{item.quantity}</span><span>{item.previousStock} → {item.newStock}</span><span>{item.createdBy || userName}</span></div>) : <p className="empty-report">No movements recorded.</p>}</div>{operation && <Operation product={product} kind={operation} close={() => openOperation(null)} submit={applyChange} />}</section></div>
}

function Operation({ product, kind, close, submit }: { product: GroceryProduct; kind: 'adjust' | 'return' | 'count'; close: () => void; submit: (productId: string, delta: number, type: InventoryMovementType, reason: string, notes: string) => Promise<void> }) {
  const [quantity, setQuantity] = useState(kind === 'count' ? String(product.stockQuantity) : ''); const [direction, setDirection] = useState<'in' | 'out'>('out'); const [reason, setReason] = useState<AdjustmentReason>('Other'); const [notes, setNotes] = useState(''); const [error, setError] = useState('')
  const save = (event: FormEvent) => { event.preventDefault(); const value = Number(quantity); const delta = kind === 'count' ? value - product.stockQuantity : (direction === 'in' ? value : -value); if (!Number.isFinite(value) || value <= 0 || (kind === 'count' && delta === 0)) return setError(kind === 'count' ? 'Physical quantity must differ from system quantity.' : 'Enter a quantity greater than zero.'); if (delta < 0 && Math.abs(delta) > product.stockQuantity) return setError(`Insufficient stock. Available quantity: ${product.stockQuantity}`); const type: InventoryMovementType = kind === 'return' ? 'return' : kind === 'adjust' && reason === 'Damaged' ? 'damage' : kind === 'adjust' && reason === 'Expired' ? 'expired' : kind === 'adjust' && reason === 'Lost' ? 'lost' : kind === 'adjust' && reason === 'Found' ? 'found' : 'adjustment'; void submit(product.id, delta, type, kind === 'count' ? 'Stock Count Correction' : reason, notes).then(close).catch(reason => setError(reason instanceof Error ? reason.message : 'Stock change was not permitted.')) }
  return <form className="operation-form" onSubmit={save}><h3>{kind === 'count' ? 'Physical Stock Count' : kind === 'return' ? 'Process Stock Return' : 'Stock Adjustment'}</h3>{kind === 'count' ? <p>System quantity: <b>{product.stockQuantity}</b></p> : <label>QUANTITY<input autoFocus type="number" min="0.01" step="0.01" value={quantity} onChange={event => setQuantity(event.target.value)} /></label>}{kind !== 'count' && <label>DIRECTION<select value={direction} onChange={event => setDirection(event.target.value as 'in' | 'out')}><option value="in">Increase stock</option><option value="out">Decrease stock</option></select></label>}{kind === 'count' ? <label>PHYSICAL QUANTITY<input autoFocus type="number" min="0" step="0.01" value={quantity} onChange={event => setQuantity(event.target.value)} /></label> : <label>REASON<select value={reason} onChange={event => setReason(event.target.value as AdjustmentReason)}>{reasons.map(item => <option key={item}>{item}</option>)}</select></label>}<label>NOTES<textarea value={notes} onChange={event => setNotes(event.target.value)} /></label>{error && <p className="validation">{error}</p>}<footer><button type="button" onClick={close}>Cancel</button><button className="confirm">Apply Change</button></footer></form>
}
