import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ReportDateRange } from './reportDateUtils'
import type { Expense } from '../../data/records'
import type { Purchase } from '../../data/purchases'
import type { Sale } from '../../data/records'

type Business = { businessName?: string; name?: string; address?: string; phone?: string }
const businessSettings = (): Business => { try { const parsed = JSON.parse(localStorage.getItem('business-settings') || '{}') as Business; return { ...parsed, phone: parsed.phone || '+94777262600' } } catch { return { phone: '+94777262600' } } }
const money = (value: number) => `Rs. ${value.toFixed(2)}`
const header = (doc: jsPDF, title: string, range: ReportDateRange) => { const business = businessSettings(); doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.text(business.businessName || business.name || 'Chicken Kade', 14, 18); doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.text([business.address, business.phone].filter(Boolean).join(' | ') || 'Business information', 14, 25); doc.setFontSize(15); doc.setFont('helvetica', 'bold'); doc.text(title, 14, 38); doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.text(`Period: ${range.start} to ${range.end}`, 14, 45); doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 51) }
const footer = (doc: jsPDF) => { const pages = doc.getNumberOfPages(); for (let page = 1; page <= pages; page++) { doc.setPage(page); doc.setFontSize(8); doc.text(`Page ${page} of ${pages}`, 190, 287, { align: 'right' }) } }
const save = (doc: jsPDF, title: string, range: ReportDateRange) => { footer(doc); doc.save(`${title.replaceAll(' ', '-')}-${range.start}${range.start === range.end ? '' : `-to-${range.end}`}.pdf`) }
export function downloadExpensePdf(report: ReturnType<typeof import('./expenseReportService').getExpenseReport>, range: ReportDateRange) { const doc = new jsPDF(); header(doc, 'EXPENSE REPORT', range); doc.setFontSize(10); doc.text(`Total Expenses: ${money(report.total)}    Count: ${report.count}    Average: ${money(report.average)}`, 14, 62); autoTable(doc, { startY: 70, head: [['Date', 'Category', 'Description', 'Payment', 'Amount']], body: report.expenses.map((item: Expense) => [item.date, item.category, item.description, item.paymentMethod, money(item.amount)]), foot: [['', '', '', 'Total Expenses', money(report.total)]], theme: 'grid', styles: { fontSize: 8 } }); autoTable(doc, { head: [['Category', 'Amount', 'Percentage']], body: report.categories.map(item => [item.category, money(item.amount), `${item.percentage.toFixed(1)}%`]), theme: 'striped', styles: { fontSize: 8 } }); save(doc, 'Expense-Report', range) }
export function downloadPurchasePdf(report: ReturnType<typeof import('./purchaseReportService').getPurchaseReport>, range: ReportDateRange) { const doc = new jsPDF(); header(doc, 'PURCHASE REPORT', range); doc.setFontSize(10); doc.text(`Total: ${money(report.total)}    Paid: ${money(report.paid)}    Outstanding: ${money(report.outstanding)}`, 14, 62); autoTable(doc, { startY: 70, head: [['Purchase No.', 'Date', 'Supplier', 'Payment', 'Total', 'Paid', 'Balance']], body: report.purchases.map((item: Purchase) => [item.purchaseNumber, item.date, item.supplierName || '-', item.paymentMethod, money(item.total), money(item.amountPaid), money(item.balanceDue)]), foot: [['', '', '', 'Totals', money(report.total), money(report.paid), money(report.outstanding)]], theme: 'grid', styles: { fontSize: 7 } }); save(doc, 'Purchase-Report', range) }
export function downloadSalesPdf(report: ReturnType<typeof import('./salesReportService').getSalesReport>, range: ReportDateRange) { const doc = new jsPDF(); const title = report.modeFilter && report.modeFilter !== 'All' ? `SALES REPORT (${report.modeFilter.toUpperCase()})` : 'SALES REPORT'; header(doc, title, range); doc.setFontSize(9); doc.text(`Total Sales: ${money(report.total)}  [Retail: ${money(report.totalRetailSales)} | Wholesale: ${money(report.totalWholesaleSales)}]    Bills: ${report.count}    Average: ${money(report.average)}`, 14, 62); autoTable(doc, { startY: 68, head: [['Method', 'Amount', 'Percentage']], body: report.paymentMethods.map(item => [item.method, money(item.amount), `${item.percentage.toFixed(1)}%`]), theme: 'striped', styles: { fontSize: 8 } }); if (report.grocery && report.grocery.length > 0) { autoTable(doc, { head: [['Product', 'Paid Qty', 'Free Qty', 'Total Given', 'Sales Amount']], body: report.grocery.map(item => [item.name, String(item.paidQuantity), String(item.freeQuantity), String(item.totalQuantity), money(item.amount)]), theme: 'grid', styles: { fontSize: 8 } }); } autoTable(doc, { head: [['Invoice', 'Date', 'Time', 'Customer', 'Cashier', 'Payment', 'Mode', 'Total']], body: report.sales.map((item: Sale) => [item.invoiceNumber, item.date, item.time, item.customerName, item.cashier, item.paymentMethod, item.sellingMode || 'RETAIL', money(item.total)]), theme: 'grid', styles: { fontSize: 7 } }); save(doc, `Sales-Report${report.modeFilter && report.modeFilter !== 'All' ? `-${report.modeFilter}` : ''}`, range) }
export function downloadProfitLossPdf(report: ReturnType<typeof import('./profitLossReportService').getProfitLossReport>, range: ReportDateRange) { const doc = new jsPDF(); header(doc, 'PROFIT & LOSS REPORT', range); doc.setFontSize(12); doc.setFont('helvetica', 'bold'); doc.text('PROFIT & LOSS STATEMENT', 14, 65); doc.setFontSize(10); doc.setFont('helvetica', 'normal'); autoTable(doc, { startY: 72, head: [['Line Item', 'Amount']], body: [['Sales Revenue', money(report.salesRevenue)], ['Grocery Sales', money(report.groceryRevenue)], ['Chicken Sales Revenue', money(report.chickenSales)], ['Grocery COGS', money(report.groceryCogs)], ['Chicken COGS', 'Not Available'], ['Gross Profit', money(report.grossProfit)], ['Operating Expenses', money(report.operatingExpenses)], [report.net >= 0 ? 'Net Profit' : 'Net Loss', money(Math.abs(report.net))], ['Gross Margin', `${report.grossMargin.toFixed(2)}%`], ['Net Margin', `${report.netMargin.toFixed(2)}%`]], theme: 'grid', styles: { fontSize: 10 }, columnStyles: { 1: { halign: 'right' } } }); save(doc, 'Profit-Loss-Report', range) }
